FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY vite.config.ts tailwind.config.js postcss.config.js index.html tsconfig.json tsconfig.node.json ./
COPY src ./src

ENV NODE_ENV=development
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 16901

CMD ["npm", "run", "dev"]
